### ISSUE TITLE
troopers curve up too sharply

### ISSUE THREAD

**Issue by DCowboy** [YeOldeDM/wangu#23]
When battle tactics gets up somewhere in the 20's there is a dramatic curve in troopers added. it's like going from 200 something to over 1300 in one click and then 1735 the click after that.

**Comment by YeOldeDM** [comment]
Troops are increased by 25% of their current value every time you level up Battle Tactics.
I think the calculation for this in the script was a little off. Spreadsheet made to double-check the formula, and the code now lines up with that.
